version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.26.2.5797-5bd057d2b
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - ALLOWED_NETWORKS=192.168.1.0/24
    network_mode: host
    volumes:
      - /opt/plex-data:/config
      - /tmp/plex-transcode:/transcode
      - /mnt/files:/data
    devices:
      - /dev/dri:/dev/dri