version: '2'
services:
  plex:
    container_name: plex
    image: my/plex-with-gpu-drivers:${TAG}
    build: './'
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - ALLOWED_NETWORKS=192.168.1.0/24
    network_mode: host
    volumes:
      - /opt/plex-data:/config
      - /tmp/plex-transcode:/transcode
      - /mnt/files:/data
      - /mnt/photo:/photo
    devices:
      - /dev/dri:/dev/dri