version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.08.0
    network_mode: "host"
    # Comment out ports and use host mode for DHCP
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "80:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      FTLCONF_dns_upstreams: '1.1.1.3;1.0.0.3;2606:4700:4700::1113;2606:4700:4700::1003'
      FTLCONF_dns_bogusPriv: 'true'
      FTLCONF_dns_domainNeeded: 'true'
      WEBPASSWORD_FILE: password
      FTLCONF_dhcp_active: 'true'
      FTLCONF_dhcp_ipv6: 'true'
      FTLCONF_dhcp_start: '192.168.1.100'
      FTLCONF_dhcp_end: '192.168.1.239'
      FTLCONF_dhcp_router: '192.168.1.1'
      FTLCONF_dns_domain: 'charlessix.local'
    volumes:
      - '/mnt/files/pihole/etc-pihole:/etc/pihole'
      - '/mnt/files/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
        #- NET_BIND_SERVICE # Allows FTLDNS binding to TCP/UDP sockets below 1024 (specifically DNS service on port 53)
        #- NET_RAW # Use raw and packet sockets (needed for handling DHCPv6 requests, and verifying that an IP is not in use before leasing it)
      - SYS_NICE # FTL sets itself as an important process to get some more processing time if the latter is running low
        #- CHOWN # We need to be able to change ownership of log files and databases in case FTL is started as a different user than pihole
        #- SYS_TIME # FTL needs to be able to set the system time to update it using the Network Time Protocol (NTP) in the background
    restart: unless-stopped
    shm_size: '2g'
