version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.05
    network_mode: "host"
    # Comment out ports and use host mode for DHCP
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "80:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      PIHOLE_DNS_: '1.1.1.3;1.0.0.3;2606:4700:4700::1113;2606:4700:4700::1003'
      DHCP_ACTIVE: true
      DNS_BOGUS_PRIV: true
      DNS_FQDN_REQUIRED: true
      DHCP_START: '192.168.1.100'
      DHCP_END: '192.168.1.239'
      DHCP_ROUTER: '192.168.1.1'
      PIHOLE_DOMAIN: 'charlessix.local'
      TEMPERATUREUNIT: 'f'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - '/mnt/files/pihole/etc-pihole:/etc/pihole'
      - '/mnt/files/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    shm_size: '2g'